require "thor"
require "shellpress/database.rb"
require "shellpress/plugins.rb"
require "shellpress/posts.rb"
require "shellpress/themes.rb"
require "shellpress/users.rb"
require "shellpress/wordpress.rb"
